package GEOGRAPHY_QUIZ;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 * The main JFrame for the Geography Quiz.
 * This class handles the logic for navigation, scorekeeping,
 * and updating the UI.
 *
 * This code is adapted to match your specific component tree.
 */
public class GeographyQuiz extends javax.swing.JFrame {
    private JButton backButton;
    private JPanel cardPanel;
    public JPanel container; // <-- This is the corrected line
    private JPanel mainPanel;
    private JPanel navigationPanel;
    private JButton nextButton;
    private JPanel panel1;
    private JPanel panel2;
    private JPanel panel3;
    private JPanel panel4;
    private JTextArea question1;
    private JTextArea question2;
    private JTextArea question3;
    private JTextArea congrats;
    private JTextField question1TextField;
    private JTextField question2TextField;
    private JTextField question3TextField;
    private JLabel scoreLabel; // This is the "Your Score: 0/3" JLabel


    // Member variables to hold the score and current panel index
    private int score;
    private int currentPanelIndex;
    private CardLayout cardLayout;

    /**
     * Creates new form GeographyQuiz
     */
    public GeographyQuiz() {
        // This method is auto-generated by the GUI builder

        // --- Custom Initialization After initComponents() ---

        // 1. Set component names (as specified in your original files)
        // This is good practice even if set in the designer.
        scoreLabel.setName("scoreLabel");
        nextButton.setName("nextButton");
        backButton.setName("backButton");

        // Panels in the CardLayout
        panel1.setName("panel1");
        panel2.setName("panel2");
        panel3.setName("panel3");
        panel4.setName("panel4");

        // Text fields
        question1TextField.setName("question1TextField");
        question2TextField.setName("question2TextField");
        question3TextField.setName("question3TextField");

        // 2. Setup CardLayout
        // This finds the CardLayout inside your 'cardPanel'
        cardLayout = (CardLayout) (cardPanel.getLayout());

        // 3. Initialize state variables
        score = 0;
        currentPanelIndex = 1; // Start at panel 1
        updateButtonVisibility(); // Set initial button state


        // 5. Add Action Listeners for buttons

        nextButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Calculate score based on all fields
                calculateScore();

                // Move to the next card
                cardLayout.next(cardPanel);
                currentPanelIndex++;
                updateButtonVisibility();
            }
        });

        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Re-calculate score in case user changes an answer
                calculateScore();

                // Move to the previous card
                cardLayout.previous(cardPanel);
                currentPanelIndex--;
                updateButtonVisibility();
            }
        });
    }

    private void initComponents() {
    }

    /**
     * Helper method to calculate the total score
     * based on the current text in all fields.
     */
    private void calculateScore() {
        score = 0; // Reset score before recalculating

        // Check answer for question 1
        if (question1TextField.getText().equalsIgnoreCase("Paris")) {
            score++;
        }

        // Check answer for question 2
        if (question2TextField.getText().equalsIgnoreCase("Tokyo")) {
            score++;
        }

        // Check answer for question 3
        if (question3TextField.getText().equalsIgnoreCase("Berlin")) {
            score++;
        }

        // Update the score label
        scoreLabel.setText("Your Score: " + score + "/3");
    }

    /**
     * Helper method to show/hide navigation buttons
     * based on the current panel.
     */
    private void updateButtonVisibility() {
        // Panel 1: No "Back"
        if (currentPanelIndex == 1) {
            backButton.setVisible(false);
            nextButton.setVisible(true);
        }
        // Panels 2 & 3: Both visible
        else if (currentPanelIndex == 2 || currentPanelIndex == 3) {
            backButton.setVisible(true);
            nextButton.setVisible(true);
        }
        // Panel 4 (Congrats): No "Next"
        else if (currentPanelIndex == 4) {
            backButton.setVisible(true);
            nextButton.setVisible(false);
        }
    }

}